import type {
  BaseStats,
  ClassDefinition,
  StarterGiftDefinition,
} from './types';

export const BASE_STARTING_STATS: BaseStats = {
  STR: 5,
  INT: 5,
  VIT: 5,
  DEX: 5,
  LUK: 5,
};

export const CHARACTER_CLASSES: ClassDefinition[] = [
  {
    id: 'warrior',
    name: 'Warrior',
    description: 'A durable frontline fighter focused on physical combat.',
    statBonus: {
      STR: 3,
      INT: 0,
      VIT: 2,
      DEX: 0,
      LUK: 0,
    },
    passive: {
      id: 'warrior_resilience',
      name: 'Resilience',
      description:
        'When HP falls below 30%, gain 15% additional damage reduction.',
    },
    starterSkills: [
      {
        id: 'slash',
        name: 'Slash',
        description: 'A direct physical strike powered by Strength.',
        actionType: 'physical_skill',
        actionCategory: 'offensive',
        effectType: 'damage',
        damageType: 'physical',
        scalingStat: 'STR',
        baseValue: 12,
        multiplier: 1.25,
        resourceType: 'Energy',
        resourceCost: 12,
        tags: ['single-target', 'physical'],
      },
      {
        id: 'guard',
        name: 'Guard',
        description: 'Raise your defense and generate a small shield.',
        actionType: 'physical_skill',
        actionCategory: 'defensive',
        effectType: 'shield',
        damageType: null,
        scalingStat: 'VIT',
        baseValue: 10,
        multiplier: 0.9,
        resourceType: 'Energy',
        resourceCost: 10,
        tags: ['shield', 'defense'],
      },
    ],
  },
  {
    id: 'mage',
    name: 'Mage',
    description: 'A spellcaster with strong magical power and mana scaling.',
    statBonus: {
      STR: 0,
      INT: 4,
      VIT: 0,
      DEX: 1,
      LUK: 0,
    },
    passive: {
      id: 'mage_focus',
      name: 'Focus',
      description:
        'After using an MP skill, the next skill gains 10% extra power.',
    },
    starterSkills: [
      {
        id: 'spark',
        name: 'Spark',
        description: 'A fast magical projectile that scales with Intelligence.',
        actionType: 'magical_spell',
        actionCategory: 'offensive',
        effectType: 'damage',
        damageType: 'magical',
        scalingStat: 'INT',
        baseValue: 14,
        multiplier: 1.35,
        resourceType: 'MP',
        resourceCost: 12,
        tags: ['single-target', 'magic'],
      },
      {
        id: 'mana_barrier',
        name: 'Mana Barrier',
        description: 'Consume mana to create a magical protective shield.',
        actionType: 'magical_spell',
        actionCategory: 'defensive',
        effectType: 'shield',
        damageType: null,
        scalingStat: 'INT',
        baseValue: 12,
        multiplier: 1.0,
        resourceType: 'MP',
        resourceCost: 14,
        tags: ['shield', 'magic', 'defense'],
      },
    ],
  },
  {
    id: 'archer',
    name: 'Archer',
    description: 'A ranged fighter with precision, speed, and critical pressure.',
    statBonus: {
      STR: 2,
      INT: 0,
      VIT: 0,
      DEX: 2,
      LUK: 1,
    },
    passive: {
      id: 'archer_sharp_instinct',
      name: 'Sharp Instinct',
      description:
        'Gain 10% bonus Crit Rate when acting first in a round.',
    },
    starterSkills: [
      {
        id: 'rapid_shot',
        name: 'Rapid Shot',
        description: 'A quick ranged attack that benefits from Dexterity.',
        actionType: 'physical_skill',
        actionCategory: 'offensive',
        effectType: 'damage',
        damageType: 'physical',
        scalingStat: 'DEX',
        baseValue: 11,
        multiplier: 1.2,
        resourceType: 'Energy',
        resourceCost: 10,
        tags: ['single-target', 'ranged'],
      },
      {
        id: 'evasion',
        name: 'Evasion',
        description: 'Increase the chance to avoid an incoming attack.',
        actionType: 'physical_skill',
        actionCategory: 'defensive',
        effectType: 'buff',
        damageType: null,
        scalingStat: 'DEX',
        baseValue: 0,
        multiplier: 0,
        resourceType: 'Energy',
        resourceCost: 12,
        tags: ['utility', 'evasion', 'self-buff'],
      },
    ],
  },
  {
    id: 'rogue',
    name: 'Rogue',
    description: 'A fast opportunist who thrives on acting before the enemy.',
    statBonus: {
      STR: 0,
      INT: 0,
      VIT: 0,
      DEX: 3,
      LUK: 2,
    },
    passive: {
      id: 'rogue_opportunity',
      name: 'Opportunity',
      description:
        'Deal 15% more damage to enemies that have not acted yet this round.',
    },
    starterSkills: [
      {
        id: 'backstab',
        name: 'Backstab',
        description: 'A precise strike that excels when used early.',
        actionType: 'physical_skill',
        actionCategory: 'offensive',
        effectType: 'damage',
        damageType: 'physical',
        scalingStat: 'DEX',
        baseValue: 13,
        multiplier: 1.3,
        resourceType: 'Energy',
        resourceCost: 14,
        tags: ['single-target', 'burst'],
      },
      {
        id: 'hide',
        name: 'Hide',
        description: 'Reduce the chance of being targeted by enemies.',
        actionType: 'physical_skill',
        actionCategory: 'utility',
        effectType: 'buff',
        damageType: null,
        scalingStat: 'DEX',
        baseValue: 0,
        multiplier: 0,
        resourceType: 'Energy',
        resourceCost: 10,
        tags: ['stealth', 'utility', 'self-buff'],
      },
    ],
  },
  {
    id: 'healer',
    name: 'Healer',
    description: 'A support-oriented caster with healing and holy magic.',
    statBonus: {
      STR: 0,
      INT: 3,
      VIT: 1,
      DEX: 0,
      LUK: 1,
    },
    passive: {
      id: 'healer_grace',
      name: 'Grace',
      description:
        'Healing effects are 15% more effective based on Intelligence.',
    },
    starterSkills: [
      {
        id: 'purify',
        name: 'Purify',
        description: 'A small magical attack with holy energy.',
        actionType: 'magical_spell',
        actionCategory: 'offensive',
        effectType: 'damage',
        damageType: 'magical',
        scalingStat: 'INT',
        baseValue: 10,
        multiplier: 1.0,
        resourceType: 'MP',
        resourceCost: 10,
        tags: ['single-target', 'holy'],
      },
      {
        id: 'heal',
        name: 'Heal',
        description: 'Restore a small amount of HP.',
        actionType: 'magical_spell',
        actionCategory: 'defensive',
        effectType: 'heal',
        damageType: null,
        scalingStat: 'INT',
        baseValue: 12,
        multiplier: 1.1,
        resourceType: 'MP',
        resourceCost: 12,
        tags: ['heal', 'support'],
      },
    ],
  },
];

export const STARTER_GIFTS: StarterGiftDefinition[] = [
  {
    id: 'stale_bread',
    name: 'Stale Bread',
    description: 'Recover 5% HP automatically after each battle.',
    effectType: 'post_battle_heal_percent',
    effectValue: 5,
  },
  {
    id: 'guide_book',
    name: 'Guide Book',
    description: 'Gain 10% faster weapon mastery progression.',
    effectType: 'weapon_mastery_bonus',
    effectValue: 10,
  },
  {
    id: 'small_pouch',
    name: 'Small Coin Pouch',
    description: 'Start your journey with 100 gold.',
    effectType: 'starting_gold',
    effectValue: 100,
  },
];

export const LOCAL_STORAGE_KEYS = {
  currentCharacter: 'magisterium.currentCharacter',
  characterArchive: 'magisterium.characterArchive',
} as const;